apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: default
spec:
  secretName: test-cert-secret
  commonName: myapp.local
  dnsNames:
  - myapp.local
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
